SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK B
JOIN  AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID 
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
GROUP BY CATEGORY, B.AUTHOR_ID
ORDER BY 1, 3 DESC;
