-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE S 
JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;