SELECT * 

FROM (SELECT CAR_ID, a.CAR_TYPE, ROUND((a.DAILY_FEE * 30) * (100 - b.DISCOUNT_RATE) * 0.01) AS FEE
FROM (SELECT car.CAR_ID, car.CAR_TYPE, car.DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR car
WHERE car.CAR_TYPE IN ('세단', 'SUV')
AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    WHERE car.CAR_ID = h.CAR_ID
    AND h.START_DATE <= '2022-11-30'
    AND h.END_DATE >= '2022-11-01'
)) a
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN b
ON a.CAR_TYPE = b.CAR_TYPE
WHERE duration_type LIKE "30%") final
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC

