-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
JOIN (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Intact%') I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE SEX_UPON_OUTCOME LIKE 'SPAYED%'
OR SEX_UPON_OUTCOME LIKE 'NEUTERED%'
ORDER BY O.ANIMAL_ID;