-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM ONLINE_SALE
JOIN (SELECT * FROM USER_INFO WHERE GENDER IS NOT NULL) I WHERE I.USER_ID = ONLINE_SALE.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1,2,3;
