-- 코드를 작성해주세요
SELECT COUNT(I.ID) AS FISH_COUNT, (SELECT FISH_NAME FROM FISH_NAME_INFO WHERE I.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE) AS FISH_NAME
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY I.FISH_TYPE
ORDER BY 1 DESC;