-- 코드를 입력하세요 
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
ROUND((COUNT(DISTINCT S.USER_ID)/ total_users),1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN (SELECT DISTINCT USER_ID FROM USER_INFO WHERE JOINED LIKE '2021%') I ON S.USER_ID = I.USER_ID
CROSS JOIN (SELECT COUNT(USER_ID) AS total_users FROM USER_INFO WHERE JOINED LIKE '2021%') total
GROUP BY YEAR, MONTH
ORDER BY 1,2; 
