-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH,
COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
ROUND((COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021)),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O 
JOIN (SELECT DISTINCT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021) U ON O.USER_iD = U.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;