WITH ICE AS(
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
   
    UNION ALL
    
    SELECT FLAVOR, TOTAL_ORDER
    FROM JULY
)

SELECT FLAVOR
FROM ICE
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3