-- 코드를 작성해주세요
WITH FRONT AS (SELECT SUM(CODE) AS SC
              FROM SKILLCODES
              WHERE CATEGORY LIKE 'Front End') 
              
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SC FROM FRONT) <> 0
ORDER BY 1;

