-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, sum(price) as TOTAL_SALES
from USED_GOODS_USER U
join USED_GOODS_BOARD B on U.USER_ID = B.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3;
