-- 코드를 작성해주세요
SELECT G.SC AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN (SELECT SUM(SCORE) AS SC, EMP_NO 
      FROM HR_GRADE GROUP BY EMP_NO ORDER BY SUM(SCORE) DESC LIMIT 1) G ON E.EMP_NO = G.EMP_NO;